using System.Globalization;
using System.Text;
using Ficep.QualityControl.Core.Sampling;

namespace Ficep.QualityControl.Core.Io;

/// <summary>
/// Writes a point cloud as an <b>ASCII PLY</b> file with one vertex element per sample
/// and the properties <c>x y z nx ny nz</c> (all <c>float</c>). PLY is the agreed scan
/// deliverable: a widely-supported format that carries per-point normals, which the
/// downstream registration / fitting step needs.
/// <para>
/// Numbers are written with invariant culture so the file is locale-independent. Header
/// follows the standard PLY 1.0 layout so the file opens in MeshLab, CloudCompare,
/// Open3D, the RobServer importer, etc.
/// </para>
/// </summary>
public sealed class PlyWriter : IPointCloudWriter
{
    /// <inheritdoc/>
    /// <exception cref="ArgumentNullException"><paramref name="path"/> or <paramref name="samples"/> is null.</exception>
    public void Write(string path, IReadOnlyList<SurfaceSample> samples)
    {
        ArgumentNullException.ThrowIfNull(path);
        ArgumentNullException.ThrowIfNull(samples);

        using var writer = new StreamWriter(path, append: false, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        WriteTo(writer, samples);
    }

    /// <summary>Writes the PLY document to an arbitrary text writer (used by <see cref="Write"/> and tests).</summary>
    public void WriteTo(TextWriter writer, IReadOnlyList<SurfaceSample> samples)
    {
        ArgumentNullException.ThrowIfNull(writer);
        ArgumentNullException.ThrowIfNull(samples);

        // Header — '\n' line endings as expected by the PLY spec, independent of platform.
        writer.NewLine = "\n";
        writer.WriteLine("ply");
        writer.WriteLine("format ascii 1.0");
        writer.WriteLine("comment generated by Ficep.QualityControl");
        writer.WriteLine($"element vertex {samples.Count}");
        writer.WriteLine("property float x");
        writer.WriteLine("property float y");
        writer.WriteLine("property float z");
        writer.WriteLine("property float nx");
        writer.WriteLine("property float ny");
        writer.WriteLine("property float nz");
        writer.WriteLine("end_header");

        // 4 decimals = 0.1 µm on positions (mm) — far finer than the ~0.1 mm range noise —
        // and 1e-4 on unit normals; trailing zeros are trimmed to keep the file compact.
        const string posFmt = "0.####";
        const string nrmFmt = "0.######";
        var ci = CultureInfo.InvariantCulture;
        foreach (SurfaceSample s in samples)
        {
            writer.Write(s.Position.X.ToString(posFmt, ci)); writer.Write(' ');
            writer.Write(s.Position.Y.ToString(posFmt, ci)); writer.Write(' ');
            writer.Write(s.Position.Z.ToString(posFmt, ci)); writer.Write(' ');
            writer.Write(s.Normal.X.ToString(nrmFmt, ci)); writer.Write(' ');
            writer.Write(s.Normal.Y.ToString(nrmFmt, ci)); writer.Write(' ');
            writer.Write(s.Normal.Z.ToString(nrmFmt, ci));
            writer.Write('\n');
        }
    }
}
